### ISSUE TITLE
Website sources

### ISSUE THREAD

**Issue by RoseWiseYT** [AlenToma/NovelManager-public#4]
Could I get the sources for all of the websites? If not then r-novel-fully, source for this one.

**Comment by AlenToma** [comment]
The reason I made it private so that it will not spread, so that the websites do not get problem and notice any us :)

My app uses the parser in a very particle way so that it dose not heavy imact the website.

It seems that you do not intend to use parser in my app! I am right? 

in anycase the public parsers sourcecode is private sorry about that.
